// src/svelte-counter.svelte
<script>
  export let count = 100;
  export let incrementAction = () => {
    console.log("count +=1", this);
  };
  export let decrementAction = () => {
    console.log("count -=1", this);
  };
</script>

<style scoped>
  div {
    display: flex;
    margin: 0 auto;
    max-width: 50%;
    align-items: center;
    justify-content: space-around;
  }
</style>

<div>
  <button on:click={decrementAction}>-</button>
  <p>{count}</p>
  <button on:click={incrementAction}>+</button>
</div>

// src/react-counter.js
import React, { Component } from 'react';
import PropTypes from 'prop-types';

export default class ReactCounter extends Component {
  render() {
    return (
            <div style={{
              display: 'flex',
              margin: '0 auto',
              maxWidth: '50%',
              alignItems: 'center',
              justifyContent: 'space-around',
            }}>
                <button onClick={this.props.decrementAction}>-</button>
                <p>{this.props.value}</p>
                <button onClick={this.props.incrementAction}>+</button>
            </div>

    );
  }
}
ReactCounter.propTypes = {
  value: PropTypes.number,
  incrementAction: PropTypes.func,
  decrementAction: PropTypes.func,
};
